import sqlite3

# Point directly to the local file generated by create_db.py, not /tmp/
DB_NAME = "mystocks.db"

def get_connection():
    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return conn

# --- CREATE ---
def add_stock(symbol, name, sector="Technology", currency="USD"):
    conn = get_connection()
    cursor = conn.cursor()
    try:
        cursor.execute("""
            INSERT INTO stocks (symbol, name, sector, currency)
            VALUES (?, ?, ?, ?)
        """, (symbol.upper(), name, sector, currency))
        conn.commit()
        print(f"Added stock: {symbol}")
    except sqlite3.IntegrityError:
        print(f"Stock {symbol} already exists.")
    finally:
        conn.close()

# --- READ ---
def get_all_stocks():
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM stocks")
    rows = cursor.fetchall()
    conn.close()
    
    print("\n--- Current Stocks ---")
    for row in rows:
        print(f"{row['id']}: {row['symbol']} - {row['name']} ({row['sector']})")
    print("----------------------\n")
    return rows

# --- UPDATE ---
def update_stock_sector(symbol, new_sector):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("""
        UPDATE stocks SET sector = ? WHERE symbol = ?
    """, (new_sector, symbol.upper()))
    conn.commit()
    print(f"Updated {symbol} sector to {new_sector}. Rows affected: {cursor.rowcount}")
    conn.close()

# --- DELETE ---
def delete_stock(symbol):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM stocks WHERE symbol = ?", (symbol.upper(),))
    conn.commit()
    print(f"Deleted {symbol}. Rows affected: {cursor.rowcount}")
    conn.close()

if __name__ == "__main__":
    print("Executing Local SQLite CRUD Operations...\n")
    
    # 1. CREATE
    add_stock("MSFT", "Microsoft Corp", "Technology")
    add_stock("TSLA", "Tesla Inc", "Automotive")
    
    # 2. READ
    get_all_stocks()
    
    # 3. UPDATE
    update_stock_sector("MSFT", "Software")
    
    # Verify Update
    get_all_stocks()
    
    # 4. DELETE
    delete_stock("TSLA")
    
    # Verify Delete
    get_all_stocks()